services:
  postgres:
    image: postgres:latest
    container_name: postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expenses
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data